# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 29d40375f3b607ef3c37c68bac669fe39ec887e18a0063b594ab7c3fc0c13a26ae2229ad37673eb71b186aa0deddb38b5f2ab3e7e3245cc5d5d49721db909e98

test:
  secret_key_base: 13039206b4ac44805509fa25aa8740ecb649c829d19eba4cf68cb4734133b08c62697f023f35d5e3220b676ec6971ee71a213729afbeeb2a503ada97bdd48ec1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
